program Micropolis;

uses
  System.StartUpCopy,
  FMX.Forms,
  MainWindow in 'gui\MainWindow.pas' {MainWindow1},
  MicropolisUnit in 'engine\MicropolisUnit.pas',
  CityBudget in 'engine\CityBudget.pas',
  JavaRandom in 'javaAPI\JavaRandom.pas',
  EarthquakeListener in 'engine\EarthquakeListener.pas',
  MapState in 'engine\MapState.pas',
  Sound in 'engine\Sound.pas',
  CityProblem in 'engine\CityProblem.pas',
  CityLocation in 'engine\CityLocation.pas',
  TileConstants in 'engine\TileConstants.pas',
  Tiles in 'engine\Tiles.pas',
  TileSpec in 'engine\TileSpec.pas',
  CityDimension in 'engine\CityDimension.pas',
  SpriteCity in 'engine\SpriteCity.pas',
  SpriteKind in 'engine\SpriteKind.pas',
  MicropolisMessage in 'engine\MicropolisMessage.pas',
  TerrainBehavior in 'engine\TerrainBehavior.pas',
  TrainSprite in 'engine\TrainSprite.pas',
  MapScanner in 'engine\MapScanner.pas',
  TrafficGen in 'engine\TrafficGen.pas',
  HelicopterSprite in 'engine\HelicopterSprite.pas',
  MonsterSprite in 'engine\MonsterSprite.pas',
  TornadoSprite in 'engine\TornadoSprite.pas',
  AirplaneSprite in 'engine\AirplaneSprite.pas',
  ShipSprite in 'engine\ShipSprite.pas',
  ToolEffectIfc in 'engine\ToolEffectIfc.pas',
  ToolEffect in 'engine\ToolEffect.pas',
  ToolResult in 'engine\ToolResult.pas',
  ToolPreview in 'engine\ToolPreview.pas',
  CityRect in 'engine\CityRect.pas',
  BudgetNumbers in 'engine\BudgetNumbers.pas',
  XML_Helper in 'XML_Helper.pas',
  ZoneStatus in 'engine\ZoneStatus.pas',
  Speed in 'engine\Speed.pas',
  GameLevel in 'engine\GameLevel.pas',
  MicropolisDrawingArea in 'gui\MicropolisDrawingArea.pas',
  TileImages in 'gui\TileImages.pas',
  TileImage in 'graphics\TileImage.pas',
  Bulldozer in 'engine\Bulldozer.pas',
  RoadLikeTool in 'engine\RoadLikeTool.pas',
  TranslatedToolEffect in 'engine\TranslatedToolEffect.pas',
  ToolStroke in 'engine\ToolStroke.pas',
  BuildingTool in 'engine\BuildingTool.pas',
  EvaluationPane in 'gui\EvaluationPane.pas',
  MessagesPane in 'gui\MessagesPane.pas',
  NotificationPane in 'gui\NotificationPane.pas',
  GraphsPane in 'gui\GraphsPane.pas',
  StringsModel in 'util\StringsModel.pas',
  TranslatedStringsTable in 'util\TranslatedStringsTable.pas',
  TranslationTool in 'util\TranslationTool.pas',
  DemandIndicator in 'gui\DemandIndicator.pas',
  OverlayMapView in 'gui\OverlayMapView.pas',
  Disaster in 'engine\Disaster.pas',
  Resources in 'javaAPI\Resources.pas',
  NewCityDialog in 'gui\NewCityDialog.pas',
  MapGenerator in 'engine\MapGenerator.pas',
  BudgetDialog in 'gui\BudgetDialog.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TMainWindow1, MainWindow1);
  Application.Run;
end.
