// This file is part of MicropolisJ.
// Copyright (C) 2013 Jason Long
// Portions Copyright (C) 1989-2007 Electronic Arts Inc.
//
// MicropolisJ is free software; you can redistribute it and/or modify
// it under the terms of the GNU GPLv3, with additional terms.
// See the README file, included in this distribution, for details.

{

/**
 * The information generated by the generateBudget function.
 * @see micropolisj.engine.Micropolis#generateBudget
 */
 }
unit BudgetNumbers;

interface

type
  TBudgetNumbers = class
  public
    TaxRate: Integer;
    TaxIncome: Integer;
    OperatingExpenses: Integer;
    PreviousBalance: Integer;
    NewBalance: Integer;

    RoadRequest: Integer;
    RoadFunded: Integer;
    RoadPercent: Double;

    FireRequest: Integer;
    FireFunded: Integer;
    FirePercent: Double;

    PoliceRequest: Integer;
    PoliceFunded: Integer;
    PolicePercent: Double;
  end;

implementation

end.
