// This file is part of MicropolisJ.
// Copyright (C) 2013 Jason Long
// Portions Copyright (C) 1989-2007 Electronic Arts Inc.
//
// MicropolisJ is free software; you can redistribute it and/or modify
// it under the terms of the GNU GPLv3, with additional terms.
// See the README file, included in this distribution, for details.



{
 * Enumeration of every possible message for the user generated by the game engine.
}
unit MicropolisMessage;

interface

type
  TMicropolisMessage = (
    NEED_RES,
    NEED_COM,
    NEED_IND,
    NEED_ROADS,
    NEED_RAILS,
    NEED_POWER,
    NEED_STADIUM,
    NEED_SEAPORT,
    NEED_AIRPORT,
    HIGH_POLLUTION,
    HIGH_CRIME,
    HIGH_TRAFFIC,
    NEED_FIRESTATION,
    NEED_POLICE,
    BLACKOUTS,
    HIGH_TAXES,
    ROADS_NEED_FUNDING,
    FIRE_NEED_FUNDING,
    POLICE_NEED_FUNDING,
    FIRE_REPORT,
    MONSTER_REPORT,
    TORNADO_REPORT,
    EARTHQUAKE_REPORT,
    PLANECRASH_REPORT,
    SHIPWRECK_REPORT,
    TRAIN_CRASH_REPORT,
    COPTER_CRASH_REPORT,
    HIGH_UNEMPLOYMENT,
    OUT_OF_FUNDS_REPORT,
    FIREBOMBING_REPORT,
    NEED_PARKS,
    EXPLOSION_REPORT,
    INSUFFICIENT_FUNDS,
    BULLDOZE_FIRST,
    POP_2K_REACHED,
    POP_10K_REACHED,
    POP_50K_REACHED,
    POP_100K_REACHED,
    POP_500K_REACHED,
    BROWNOUTS_REPORT,
    HEAVY_TRAFFIC_REPORT,
    FLOOD_REPORT,
    MELTDOWN_REPORT,
    RIOTING_REPORT,
    NO_NUCLEAR_PLANTS,
    NONE
  );

function UsesNotificationPane(Msg: TMicropolisMessage): Boolean;
function mmToSting(Msg: TMicropolisMessage):String;

implementation

function UsesNotificationPane(Msg: TMicropolisMessage): Boolean;
begin
  case Msg of
    // Non-location-specific
    POP_2K_REACHED,
    POP_10K_REACHED,
    POP_50K_REACHED,
    POP_100K_REACHED,
    POP_500K_REACHED,
    HIGH_CRIME,
    HIGH_POLLUTION,

    // Location-specific
    FLOOD_REPORT,
    FIRE_REPORT,
    TORNADO_REPORT,
    MELTDOWN_REPORT,
    EARTHQUAKE_REPORT,
    TRAIN_CRASH_REPORT,
    SHIPWRECK_REPORT,
    COPTER_CRASH_REPORT,
    PLANECRASH_REPORT:
      Result := True;
  else
    Result := False;
  end;
end;

function mmToSting(Msg: TMicropolisMessage):String;
begin
  case Msg of
    NEED_RES	: Result :='NEED_RES';
    NEED_COM	: Result :='NEED_COM';
    NEED_IND	: Result :='NEED_IND';
    NEED_ROADS	: Result :='NEED_ROADS';
    NEED_RAILS	: Result :='NEED_RAILS';
    NEED_POWER	: Result :='NEED_POWER';
    NEED_STADIUM	: Result :='NEED_STADIUM';
    NEED_SEAPORT	: Result :='NEED_SEAPORT';
    NEED_AIRPORT	: Result :='NEED_AIRPORT';
    HIGH_POLLUTION	: Result :='HIGH_POLLUTION';
    HIGH_CRIME	: Result :='HIGH_CRIME';
    HIGH_TRAFFIC	: Result :='HIGH_TRAFFIC';
    NEED_FIRESTATION	: Result :='NEED_FIRESTATION';
    NEED_POLICE	: Result :='NEED_POLICE';
    BLACKOUTS	: Result :='BLACKOUTS';
    HIGH_TAXES	: Result :='HIGH_TAXES';
    ROADS_NEED_FUNDING	: Result :='ROADS_NEED_FUNDING';
    FIRE_NEED_FUNDING	: Result :='FIRE_NEED_FUNDING';
    POLICE_NEED_FUNDING	: Result :='POLICE_NEED_FUNDING';
    FIRE_REPORT	: Result :='FIRE_REPORT';
    MONSTER_REPORT	: Result :='MONSTER_REPORT';
    TORNADO_REPORT	: Result :='TORNADO_REPORT';
    EARTHQUAKE_REPORT	: Result :='EARTHQUAKE_REPORT';
    PLANECRASH_REPORT	: Result :='PLANECRASH_REPORT';
    SHIPWRECK_REPORT	: Result :='SHIPWRECK_REPORT';
    TRAIN_CRASH_REPORT	: Result :='TRAIN_CRASH_REPORT';
    COPTER_CRASH_REPORT	: Result :='COPTER_CRASH_REPORT';
    HIGH_UNEMPLOYMENT	: Result :='HIGH_UNEMPLOYMENT';
    OUT_OF_FUNDS_REPORT	: Result :='OUT_OF_FUNDS_REPORT';
    FIREBOMBING_REPORT	: Result :='FIREBOMBING_REPORT';
    NEED_PARKS	: Result :='NEED_PARKS  ';
    EXPLOSION_REPORT	: Result :='EXPLOSION_REPORT';
    INSUFFICIENT_FUNDS	: Result :='INSUFFICIENT_FUNDS';
    BULLDOZE_FIRST	: Result :='BULLDOZE_FIRST';
    POP_2K_REACHED	: Result :='POP_2K_REACHED';
    POP_10K_REACHED	: Result :='POP_10K_REACHED';
    POP_50K_REACHED	: Result :='POP_50K_REACHED';
    POP_100K_REACHED	: Result :='POP_100K_REACHED';
    POP_500K_REACHED	: Result :='POP_500K_REACHED';
    BROWNOUTS_REPORT	: Result :='BROWNOUTS_REPORT';
    HEAVY_TRAFFIC_REPORT	: Result :='HEAVY_TRAFFIC_REPORT';
    FLOOD_REPORT	: Result :='FLOOD_REPORT';
    MELTDOWN_REPORT	: Result :='MELTDOWN_REPORT';
    RIOTING_REPORT	: Result :='RIOTING_REPORT';
    NO_NUCLEAR_PLANTS	: Result :='NO_NUCLEAR_PLANTS';
    NONE	: Result :='NONE';
  end;
end;

end.