// This file is part of MicropolisJ.
// Copyright (C) 2013 Jason Long
// Portions Copyright (C) 1989-2007 Electronic Arts Inc.
//
// MicropolisJ is free software; you can redistribute it and/or modify
// it under the terms of the GNU GPLv3, with additional terms.
// See the README file, included in this distribution, for details.



{
 * Contains the information generated by the query tool.
 * The numbers have very limited use, they are interpreted directly
 * by the showZoneStatus() method of NotificationPane.
}
unit ZoneStatus;

interface

type
  TZoneStatus = record
    Building: Integer;    // 0..27, type of building
    PopDensity: Integer;  // 1..4, 1=Low, 2=Medium, 3=High, 4=Very High
    LandValue: Integer;   // 5..8, 5=Slum, 6=Lower Class, etc.
    CrimeLevel: Integer;  // 9..12, 9=Safe, 10=Light, 11=Moderate, etc.
    Pollution: Integer;   // 13..16, 13=None, 14=Moderate, 15=Heavy, etc.
    GrowthRate: Integer;  // 17..20, 17=Declining, 18=Stable, etc.
  end;

implementation

end.